{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    "@semantic-release/git"
  ],
  "github": {
    "assets": [
      {
        "path": "generated-passports.zip",
        "label": "PDF Passports"
      }
    ]
  }
}