{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/exec",
      {
        "publishCmd": "./gradlew run && zip -r generated-passports.zip generated"
      }
    ],
    "@semantic-release/github",
    "@semantic-release/git"
  ],
  "github": {
    "assets": [
      {
        "path": "generated-passports.zip",
        "label": "PDF Passports"
      }
    ]
  }
}