name: Build and Test

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

  pull_request:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build-test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build and test
        run: ./gradlew build

      - name: Publish Test Report
        if: always() # runs even if tests fail
        uses: dorny/test-reporter@v1
        with:
          name: Kotlin Test Report
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit