name: Build and Test

on:
  workflow_dispatch:

  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Build and test
        run: ./gradlew build

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Kotlin Test Report
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit